-- Ignite 3 table definitions for Watts4Homes
-- Run these manually after "cluster init", they are not created automatically.
-- Column names must match the POJO field names (HomeState, ApplianceBreachState).

CREATE TABLE IF NOT EXISTS HOME_STATE (
    ID BIGINT PRIMARY KEY,
    ACCUMULATEDUSAGE DOUBLE,
    ACCUMULATEDCOST DOUBLE,
    TARIFFSTATE VARCHAR,
    BUDGETQUOTA DOUBLE,
    CURRENTRATE DOUBLE,
    PENALTYRATE DOUBLE,
    BREACHEDEIGHTYPERCENT BOOLEAN,
    BREACHEDHUNDREDPERCENT BOOLEAN
);

CREATE TABLE IF NOT EXISTS APPLIANCE_BREACH (
    ID VARCHAR PRIMARY KEY,
    SAFELIMITWATTS DOUBLE,
    CONSECUTIVEBREACHCOUNT INT,
    LASTSTATUS VARCHAR
);